export const tracks = [
  {
    title: "Cruel Summer",
    info: "Taylor Swift",
    image: "./assets/album/cruel_summer.png",
    audio: "./assets/songs/cruel_summer.mp3",
    video: "./assets/videos/Taylor_Swift_-_Cruel_Summer___Spotify_Canvas(720p).mp4",
  },
  {
    title: "Payal",
    info: "Yo Yo Honey Singh, Nora Fatehi, Paradox",
    image: "./assets/album/glory.png",
    audio: "./assets/songs/payal.mp3",
    video: "./assets/videos/Payal__Yo_Yo_Honey_Singh,_Nora_Fatehi,_Paradox.mp4",
  },
  {
    title: "Birds of a Feather",
    info: "Billie Eilish",
    image: "./assets/album/birds_of_feather.png",
    audio: "./assets/songs/birds_of_feather.mp3",
    video: "./assets/videos/Watch_the_BIRDS_OF_A_FEATHER.mp4",
  },
  {
    title: "Die With A Smile",
    info: "Lady Gaga, Bruno Mars",
    image: "./assets/album/lady_gaga.png",
    audio: "./assets/songs/die_with_smile.mp3",
    video: "./assets/videos/Lady_Gaga,_Bruno_Mars_-_Die_With_A_Smile.mp4",
  },
  {
    title: "Hey Minnale",
    info: "Haricharan, Shweta Mohan, G. V. Prakash",
    image: "./assets/album/hey_minnale.png",
    audio: "./assets/songs/hey_minnale.mp3",
    video: "./assets/videos/Hey_Minnale.mp4",
  },
  {
    title: "Hass Hass",
    info: "Diljit Dosanjh, Greg Kurstin, and Sia",
    image: "./assets/album/hass_hass.png",
    audio: "./assets/songs/hass_hass.mp3",
    video: "./assets/videos/Hass_Hass.mp4",
  },
  {
    title: "Mere Mehboob",
    info: "Sachin-Jigar,Shilpa,Sachet",
    image: "./assets/album/mere_mehboob.png",
    audio: "./assets/songs/mere_mehboob.mp3",
    video: "./assets/videos/Mere_Mehboob_Tera_Tadpna_Toh_Banta_Hai_Triptii_Dimri,_Rajkummar.mp4",
  },
  {
    title: "Oo Antava",
    info: "Devi Sri Prasad",
    image: "./assets/album/oo_antava.png",
    audio: "./assets/songs/oo_antava.mp3",
    video: "./assets/videos/Oo_Antava_Song___Pushpa_Song.mp4",
  },
  {
    title: "Round and Round",
    info: "Free Bird",
    image: "./assets/album/round_and_round.png",
    audio: "./assets/songs/mingle_song.mp3",
    video: "./assets/videos/Squid_Game_S2_Song___Mingle_Song___Round___Round___Ring-a-Ring.mp4",
  },
  {
    title: "Jo Tum Mere Ho",
    info: "Anuv Jain",
    image: "./assets/album/jo_tum_mere_ho.png",
    audio: "./assets/songs/jo_tum_mere_ho.mp3",
    video: "./assets/videos/Jo_Tum_mere_ho_–_Anuv_Jain.mp4",
  },
];
